baseURL = "https://exo-cortex.github.io/"
languageCode = "en-us"
title = "exo-cortex: weblog"
theme="archie"

# copyright = "© Athul"

# Code Highlight
pygmentsstyle = "pygments"
# pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="light" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "space for my thoughts"
	# subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/exo-cortex"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/athulcajay/"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "how-to"
url = "/how-to"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "blogroll"
url = "/blogroll/blogroll"
weight = 4

[[menu.main]]
name = "about"
url = "/about/about/"
weight = 5
