# The URL the site will be built for
base_url = "https://exo-cortex.github.io"
title = "exo-cortex"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "tags" },
]

[markdown]

[markdown.highlighting]
theme = "ayu-dark"
# dark_theme = "ayu-dark"
# light_theme = "ayu-light"

[extra]
author = "exo-cortex"
subtitle = "space for my thoughts"
